<?php
set_time_limit(0);
# Use the Curl extension to query Google and get back a page of results

$arrStartArray = getURLData("https://freedailyiptv.com/world-m3u-free-daily-iptv-list-" . date("m-Y") . "/", 'a');

$arrSecondURLs = getURLData('http://vlctest.eu5.net/', 'span');
$arrFirstURLs = getURLData('https://www.oneplaylist.space/', 'span');

$i = 0;
do {
	$strCurrentTime = getDateTime($i);
	$url = "https://www.en.m3uiptv.com/iptv-links-free-m3u-playlist-$strCurrentTime/";
	echo $strCurrentTime . PHP_EOL;
	$i++;
} while (get_http_response_code($url) != "200" && $i < 10);

$arrURLs = getURLData($url, 'pre');
$arrURLs = array_unique(array_merge($arrStartArray, $arrFirstURLs, $arrSecondURLs, $arrURLs));

//$arrURLs = array('https://freedailyiptv.com/links/25-02-2019/World20_freedailyiptv.com.m3u');
$strFinal = '';
$stradtFinal = '';
$strChannelCount = 0;
$context = stream_context_create(array('http' => array('timeout' => 5)));
foreach ($arrURLs as $index => $strURL) {
	if (strpos($strURL, 'http') === false || strpos($strURL, 'm3u') === false) {
		unset($arrURLs[$index]);
		continue;
	}
	echo $strURL . PHP_EOL;
	if (get_http_response_code($strURL) != "200" || empty($strURL)) {
		unset($arrURLs[$index]);
		continue;
	} else {
		$strContent = file_get_contents($strURL);
	}
	
	/*if ($strChannelCount >= 500) {
		unset($arrURLs[$index]);
		continue;
	}*/

	$arrstrContent = explode('#EXTINF', $strContent);
	unset($strContent);
	foreach ($arrstrContent as $value) {
		if (preg_match('(hindi:|english:|marathi:|in:|in-|\(in\)|in\||in \||hindi \||hindi\||english\||english \||marathi\||marathi \||adt|xxx)', strtolower($value)) === 1) {
			$strgroupTitle = $index;

			if (strpos(strtolower($value), 'hd') !== false) {
				$strgroupTitle = 'HD ' . $index;
				$url = trim(explode(PHP_EOL, $value)[1]);
				if (!$fp = @fopen($url, "r", false, $context)) {
					//echo "FAiled ==>" . explode(PHP_EOL, $value)[1];
				} else {
					if (preg_match('(adt|xxx)', strtolower($value)) === 1) {
						$stradtFinal .= '#EXTINF' . str_replace(array(':-1,', ':0,'), array(':-1,' . ' group-title=\"' . $strgroupTitle . '\", ', ':0,' . ' group-title=\"' . $strgroupTitle . '\", '), addslashes($value)) . PHP_EOL;
					} else {
						$strFinal .= '#EXTINF' . str_replace(array(':-1,', ':0,'), array(':-1,' . ' group-title=\"' . $strgroupTitle . '\", ', ':0,' . ' group-title=\"' . $strgroupTitle . '\", '), addslashes($value)) . PHP_EOL;
						$strChannelCount++;
					}
					fclose($fp);
				}
			}
		}
	}
}
/*$myfile = fopen("newfile.m3u", "w") or die("Unable to open file!");
fwrite($myfile, $strFinal);
fclose($myfile);*/
if (false == empty($strFinal)) {
	echo "Writing in the paste URL";
	writeFile($strFinal, 'f9p029xslv', 'Channels');
}

if (false == empty($stradtFinal)) {
	echo "Writing in the paste URL";
	writeFile($stradtFinal, 'f9tkwi5gse', 'ADT');
}

exit;

function get_http_response_code($url) {
	$headers = get_headers($url);
	return substr($headers[0], 9, 3);
}

function getDateTime($intInvertDays) {
	$objDateTime = new DateTime();
	$objDateTime->setTimeZone(new DateTimeZone('IST'));
	$strDateInterval = new DateInterval("P" . $intInvertDays . "D");
	$strDateInterval->invert = 1;
	$objDateTime->add($strDateInterval);
	return $objDateTime->format('d-m-Y');
}

function getURLData($url, $strTag) {
	$arrURLs = array();
	$arrFinalArray = array();

	$ch = curl_init();
	$timeout = 5;
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
	$html = curl_exec($ch);
	curl_close($ch);

	# Create a DOM parser object
	$dom = new DOMDocument();
# Parse the HTML from Google.
	# The @ before the method call suppresses any warnings that
	# loadHTML might throw because of invalid HTML in the page.
	@$dom->loadHTML($html);

# Iterate over all the <a> tags
	foreach ($dom->getElementsByTagName($strTag) as $link) {
		# Show the <a href>
		$arrURLs = array_map('trim', explode(PHP_EOL, $link->nodeValue));
		$arrURLs = array_filter($arrURLs);
		$arrFinalArray = array_merge($arrFinalArray, $arrURLs);
	}

	return array_filter($arrFinalArray, 'removeInvalidLinks');
}

function removeInvalidLinks($var) {
	// returns whether the value is 'other'
	return (strpos($var, 'http') !== false);
}

function writeFile($strFinal, $strFileName, $strChannel) {
	$strFinal = '#EXTM3U' . PHP_EOL . $strFinal;
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'https://snippets.glot.io/snippets/' . $strFileName);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	//curl_setopt($ch, CURLOPT_POSTFIELDSIZE, -1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"language\": \"plaintext\", \"title\": \"$strChannel\", \"public\": false, \"files\": [{\"name\": \"main.txt\", \"content\": \"" . $strFinal . "\"}]}");
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
	$headers = array();
	$headers[] = 'Authorization: Token a48c4968-8309-4374-8431-f43b92f21ad3';
	$headers[] = 'Content-Type: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$result = curl_exec($ch);

	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
}
?>
